<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{0ca78153-12a1-425f-a0ef-fffe244bf1e5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbXmlRead	:	FB_XMLRead;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbXmlRead();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>